FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ARG VITE_GOOGLE_CLIENT_ID
ENV VITE_GOOGLE_CLIENT_ID=$VITE_GOOGLE_CLIENT_ID

RUN npm run build


FROM nginx:alpine

COPY --from=0 /app/dist /usr/share/nginx/html
# THIS LINE
COPY nginx.conf /etc/nginx/conf.d/default.conf   

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
