services:
  db:
    image: postgres:15
    container_name: iot-db
    restart: always
    environment:
      POSTGRES_DB: iot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 10

  backend:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - 8000:8000
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: iot
      DB_USER: postgres
      DB_PASSWORD: postgres

  frontend:
    build:
      context: ./frontend
      args:
        VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID}
    container_name: iot-frontend
    depends_on:
      - backend
    ports:
      - "80:80"   # users visit localhost
      - "443:443"
    volumes:
      - ./nginx-certs:/etc/nginx-certs

volumes:
  postgres_data:
